server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    service.name: DEPARTMENT-SERVICE
    sender.type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
